name: CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build:
    name: Build, Type Check, Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Run test cases
        run: npm run test:run
        working-directory: backend

      - name: Type check
        run: npm run type-check
        working-directory: backend

      - name: Running ESlint check and fix
        run: npm run lint:fix
        working-directory: backend

      - name: Running format check and fix
        run: npm run format
        working-directory: backend

      - name: Lint check for remaining ESlint issues
        run: npm run lint
        working-directory: backend

      - name: Format check for remaining formatting issues
        run: npm run format:check
        working-directory: backend